[package]
name = "gco"
version = "0.1.0"
authors = ["Benjamin Wagner <bewagner@uni-bremen.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.27.0"
git2 = "0.13.3"
regex = "1"
